### ISSUE TITLE
Update Data?

### ISSUE THREAD

**Issue by drony** [StefH/GraphQL.EntityFrameworkCore.DynamicLinq#4]
Is it possible insert or update data?

**Comment by StefH** [comment]
Only for query.

**Comment by drony** [comment]
any plan for implementing in future?

**Comment by StefH** [comment]
I would not know how to implement this. Do you have any ideas?

**Comment by drony** [comment]
i'm very new to graphql. i think graphql mutation feature allow this? but i need a wrapper like this framework. i need complete solution for querying and updating data. By the way this lib is awesome so far. keep forward

**Comment by StefH** [comment]
For an example project which uses this library and implements mutation.https://github.com/StefH/ASPNetCoreGraphQL/blob/master/src/MyHotel3/GraphQL/MyHotelSchema.cs#L11

**Comment by drony** [comment]
thanks i will check out
