### ISSUE TITLE
ListGraphType property declaration fails to resolve schema

### ISSUE THREAD

**Issue by thesobercoder** [StefH/GraphQL.EntityFrameworkCore.DynamicLinq#5]
Declaring a `ListGraphType` inside a graphql object fails to resolve schema - 

Please take a look at the full sample here at this [link](https://github.com/thesobercoder/GraphQLTest/blob/master/GraphQL.Api/TestHarness.cs).

``` c#
public class CustomerGraph : ObjectGraphType<Customer>
{
	public CustomerGraph()
	{
		Name = "Customer";
		Field(x => x.CustomerID);
		Field(x => x.CustomerName);
	        //Commenting out the below line makes it work
		Field<ListGraphType<OrderGraph>>("Orders", resolve: context => context.Source.Orders);
	}
}
```

**Comment by StefH** [comment]
Thanks for reporting this.

This functionality is not yet implemented, I'll take a look.

**Comment by StefH** [comment]
I think it just works fine.

However you need to add an `Include(c => c.Orders)` for the cusometers?
``` c#
var customerArguments = builder.Build<CustomerGraph>().SupportOrderBy();
            Field<ListGraphType<CustomerGraph>>("customers",
                arguments: customerArguments.ToQueryArguments(),
                resolve: context => dbcontext.Customers.Include(c => c.Orders).ApplyQueryArguments(customerArguments, context)
            );
```

Result is like:
``` js
{
  "data": {
    "customers": [
      {
        "customerName": "Facebook",
        "orders": [
          {
            "orderID": 1,
            "orderDate": "2020-01-11"
          },
          {
            "orderID": 2,
            "orderDate": "2020-01-11"
          }
        ]
      },
      {
        "customerName": "Microsoft",
        "orders": [
          {
            "orderID": 3,
            "orderDate": "2020-01-11"
          }
        ]
      }
    ]
  }
}
```

**Comment by thesobercoder** [comment]
Yeah it seems to work just fine. I got confused by Playground UI not being able to resolve the schema which I thought was a problem. As you can see below the query works fine but schema won't load. Not sure why that is happening though.

![image](https://user-images.githubusercontent.com/1915249/72208984-8a37aa80-34cf-11ea-882f-a56a156039cd.png)

**Comment by thesobercoder** [comment]
On a different note-

If I issue the query 

```
query {
  customers {
    customerID
    orders {
      orderID
    }
  }
}
```

EntityFramework still ends up querying all columns like so - 

```
SELECT [c].[CustomerID], [c].[CustomerName], [o].[OrderID], [o].[CustomerID], [o].[OrderDate]
FROM [Customers] AS [c]
LEFT JOIN [Orders] AS [o] ON [c].[CustomerID] = [o].[CustomerID]
ORDER BY [c].[CustomerID], [o].[OrderID]
```

Is there something we can do about partially selecting columns?

**Comment by StefH** [comment]
1. Schema won't load due to an javascript error:
``` js
invariant.js:18 Uncaught Error: Introspection must provide input type for arguments.
    at r (invariant.js:18)
    at r (buildClientSchema.js:111)
    at A (buildClientSchema.js:250)
    at keyValMap.js:28
    at Array.reduce (<anonymous>)
    at r (keyValMap.js:27)
    at k (buildClientSchema.js:244)
    at buildClientSchema.js:238
    at keyValMap.js:28
    at Array.reduce (<anonymous>)
```
Not sure if this was always the case, or only introduced when using a ListGraphType, I need to check.


2]
_EntityFramework still ends up querying all columns like so_ I know, this is a limitation for this project. I did not have time to build this code. (Maybe create a new issue to track this?)

**Comment by thesobercoder** [comment]
1. I noticed that if you comment out the `ListGraphType` this error goes away.
2. I'll open a new issue for that.

**Comment by StefH** [comment]
@thesobercoder Can you please try version GraphQL.EntityFrameworkCore.DynamicLinq.1.0.2-ci-12477.nupkg ?

Note that you need an extra configuration option to get it working, see my example projects.

**Comment by thesobercoder** [comment]
@StefH I tested it with version GraphQL.EntityFrameworkCore.DynamicLinq.1.0.2-ci-12490.nupkg and it works absolutely fine.

**Comment by StefH** [comment]
About the configuration: I don't know yet.

Because the code works. However an Any is used, so unless the 'select' is implemented, you get possibly wrong result. You can try this in your example which I copied in my project.

And only one nested level is supported. So it's not yet perfect.

I will create an official NuGet soon and start on the 'select' issue.
